version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: carga
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
